[package]
name = "wiperf"
version = "0.1.0"
authors = ["Olli Paakkunainen <olli@paakkunainen.fi>", "Adarsh Krishnan <adarshk7@gmail.com>"]
edition = "2018"

[dependencies]
ctrlc = "3.1.4"
crossbeam-channel = "0.4.2"
