[package]
name = "uption"
version = "0.2.1"
authors = ["Olli Paakkunainen <olli@paakkunainen.fi>", "Adarsh Krishnan <adarshk7@gmail.com>"]
description = """
A tool to collect and export network performance metrics on devices like
WLAN Pi and Raspberry Pi.
"""
readme = "README.md"
license = "MIT"
keywords = ["network", "wifi", "metrics"]
categories = ["command-line-utilities"]
edition = "2018"
homepage = "https://github.com/uption/uption"
repository = "https://github.com/uption/uption"
documentation = "https://github.com/uption/uption"
exclude = [".github/*"]

[dependencies]
ctrlc = "3.1"
crossbeam-channel = "0.4"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
regex = "1.3"
url = { version = "2.1", features = ["serde"] }
http_req  = { version = "0.6", default-features = false, features = ["rust-tls"] }
config = "0.10"
rand = "0.7"

[package.metadata.deb]
license-file = ["LICENSE"]
depends = "$auto, systemd"
section = "utils"
priority = "optional"
assets = [
    ["target/release/uption", "usr/bin/", "755"],
    ["uption.toml", "etc/uption/", "644"],
    ["build/uption.service", "/etc/systemd/system/", "644"],
]
