# See all the configuration options from Uption documentation:
# https://github.com/uption/uption/wiki/Configuration
[general]
hostname = "uption-host-1"

[logging]
level = "info"

[collectors]
interval = 10

[collectors.ping]
enabled = true
hosts = ["example.com", "93.184.216.34"]

[collectors.http]
enabled = true
urls = ["http://example.com/"]

[collectors.dns]
dns_servers = []
enabled = false
hosts = []

[collectors.wireless]
enabled = false

[exporters]
exporter = "stdout"
