[general]
hostname = "uption-host-1"

[collectors]
interval = 10

[collectors.ping]
enabled = true
hosts = ["example.com", "93.184.216.34"]

[collectors.http]
enabled = true
timeout = 10
urls = ["http://example.com/"]

[exporters]
exporter = "stdout"

[exporters.influxdb]
# url = ""
# bucket = ""
# organization = ""
# token = ""
