[general]
hostname = "uption-host-1"

[collectors]
interval = 10

[collectors.ping]
enabled = true
hosts = []

[collectors.http]
enabled = true
timeout = 10
urls = []

[exporters]
exporter = "stdout"

[exporters.influxdb]
# url = ""
# bucket = ""
# organization = ""
# token = ""
