name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    name: Build crate and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --locked

      - name: Run unit tests
        run: cargo test

      - name: Run integration tests
        run: cargo test -- --ignored

  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  format:
    name: Run formatter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check

  block-autosquash-commits:
    name: Block autosquash commits
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'

    steps:
      - name: Block autosquash commits
        uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
